all:
	nvcc -arch=sm_61 main.cu && ./a.out ./input/stable.par
	nvcc -arch=sm_61 main.cu && ./a.out ./input/repell.par
	nvcc -arch=sm_61 main.cu && ./a.out ./input/attract.par
	nvcc -arch=sm_61 main.cu && ./a.out ./input/blocks.par
